In [2]:
import numpy as np

In [3]:
#1. Create an array of 10 zeros
arr=np.zeros(10)

In [4]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#2. Create an array of 10 ones
arr1=np.ones(10)

In [6]:
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
#3. Create an array of 10 fives
arr2=arr + 5
arr3=arr1 * 5

In [8]:
arr2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
#4. Create an array of the integers from 10 to 50
arr4=np.arange(10,51)

In [13]:
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [17]:
#5. Create an array of all the even integers from 10 to 50
arr5=np.arange(10,51,2)

In [18]:
arr5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [22]:
#6. Create a 3x3 matrix with values ranging from 0 to 8
arr6=np.arange(0,9)
arr6.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
#7. Create a 3x3 identity matrix
arr7=np.eye(3,3)

In [25]:
arr7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
#8. Use NumPy to generate a random number between 0 and 1
np.random.rand(0,1)

array([], shape=(0, 1), dtype=float64)

In [28]:
np.random.rand(1)

array([0.16712506])

In [30]:
#9. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
arr8=np.random.randn(25)

In [31]:
arr8

array([ 0.90963755,  0.44644799, -0.41464767,  0.01238367, -1.44870982,
       -0.11902606,  0.44296341, -0.04134882, -1.41534471,  1.14000818,
        0.89026105,  0.43780066, -1.1259904 ,  0.5572698 ,  0.91475809,
       -1.87148592,  0.80423192, -0.840184  , -0.21496697,  1.77911426,
        0.9548048 ,  0.14648761,  0.64369925,  1.29695467,  0.1100359 ])

In [36]:
#10. Create the following matrix:
arr9=np.arange(1,101)
arr10=arr9*1/100
arr10
arr10.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [37]:
#11. Create an array of 20 linearly spaced points between 0 and 1:
arr11=np.linspace(0,1,20)

In [38]:
arr11

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

In [39]:
arr12=np.arange(1,26).reshape(5,5)
arr12

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
#12. WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
arr12[2:,1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [43]:
#13. WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
arr12[3,4]

20

In [44]:
#14. WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
arr12

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
arr12[:3,1]

array([ 2,  7, 12])

In [48]:
arr12[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [49]:
#15. WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
##array([21, 22, 23, 24, 25])
arr12[4,0:]

array([21, 22, 23, 24, 25])

In [50]:
#16. WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
# array([[16, 17, 18, 19, 20],
#       [21, 22, 23, 24, 25]])
arr12[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
#17. Get the sum of all the values in mat
arr12.sum()

325

In [52]:
np.sum(arr12)

325

In [56]:
#18. Get the standard deviation of the values in mat
np.std(arr12)

7.211102550927978

In [54]:
#19. Get the sum of all the columns in mat

In [58]:
np.sum(arr12,axis=0)

array([55, 60, 65, 70, 75])